import { EnemyTypeEnum, EnemyType, EnemyAttackType, EnemyStats } from '../types'

export const ENEMY_ATTACK_TYPES: Record<string, EnemyAttackType> = {
  explode: {
    attackDist: 30,
    attackDelay: 750,
    launchSpeed: 200,
    isExplode: true,
    damage: 5,
  },
  slash: {
    attackDist: 30,
    attackDelay: 750,
    launchSpeed: 0,
    isExplode: false,
    damage: 5,
  },
}

export const ENEMY_STATS: Record<string, EnemyStats> = {
  imp: {
    key: 'imp',
    attackType: ENEMY_ATTACK_TYPES['slash'],
    health: 1,
    speed: 80,
    collideDamage: 1,
    stunDuration: 1000,
    stunSpeed: 250,
  },
  demon: {
    key: 'demon',
    attackType: ENEMY_ATTACK_TYPES['explode'],
    health: 2,
    speed: 50,
    collideDamage: 1,
    stunDuration: 1000,
    stunSpeed: 250,
  },
  chort: {
    key: 'chort',
    attackType: ENEMY_ATTACK_TYPES['explode'],
    health: 2,
    speed: 50,
    collideDamage: 1,
    stunDuration: 1000,
    stunSpeed: 250,
  },
  orc: {
    key: 'orc',
    attackType: ENEMY_ATTACK_TYPES['explode'],
    health: 2,
    speed: 50,
    collideDamage: 1,
    stunDuration: 1000,
    stunSpeed: 250,
  },
  ogre: {
    key: 'ogre',
    attackType: ENEMY_ATTACK_TYPES['explode'],
    health: 2,
    speed: 50,
    collideDamage: 1,
    stunDuration: 1000,
    stunSpeed: 250,
  },
  goblin: {
    key: 'goblin',
    attackType: ENEMY_ATTACK_TYPES['explode'],
    health: 2,
    speed: 50,
    collideDamage: 1,
    stunDuration: 1000,
    stunSpeed: 250,
  },
  lizard: {
    key: 'lizard',
    attackType: ENEMY_ATTACK_TYPES['slash'],
    health: 2,
    speed: 50,
    collideDamage: 1,
    stunDuration: 1000,
    stunSpeed: 250,
  },
  skele: {
    key: 'skele',
    attackType: ENEMY_ATTACK_TYPES['slash'],
    health: 2,
    speed: 50,
    collideDamage: 1,
    stunDuration: 1000,
    stunSpeed: 250,
  },
}

export const ENEMY_TYPES: Record<EnemyTypeEnum, EnemyType> = {
  orc: {
    key: 'orc',
    offsetX: 4,
    offsetY: 11,
    offsetHealth: -30,
    offsetShadow: 35,
    sizeX: 8,
    sizeY: 8,
  },
  ogre: {
    key: 'ogre',
    offsetX: 12,
    offsetY: 24,
    offsetHealth: -40,
    offsetShadow: 55,
    sizeX: 8,
    sizeY: 8,
  },
  goblin: {
    key: 'goblin',
    offsetX: 4,
    offsetY: 8,
    offsetHealth: -35,
    offsetShadow: 25,
    sizeX: 8,
    sizeY: 8,
  },
  imp: {
    key: 'imp',
    offsetX: 4,
    offsetY: 8,
    offsetHealth: -35,
    offsetShadow: 25,
    sizeX: 8,
    sizeY: 8,
  },
  chort: {
    key: 'chort',
    offsetX: 4,
    offsetY: 13,
    offsetHealth: -30,
    offsetShadow: 36,
    sizeX: 8,
    sizeY: 8,
  },
  demon: {
    key: 'demon',
    offsetX: 12,
    offsetY: 24,
    offsetHealth: -40,
    offsetShadow: 55,
    sizeX: 8,
    sizeY: 8,
  },
  skele: {
    key: 'skele',
    offsetX: 4,
    offsetY: 6,
    offsetHealth: -35,
    offsetShadow: 25,
    sizeX: 8,
    sizeY: 8,
  },
  lizard: {
    key: 'lizard',
    offsetX: 4,
    offsetY: 18,
    offsetHealth: -28,
    offsetShadow: 42,
    sizeX: 8,
    sizeY: 8,
  },
}
