import { EnemyTypeEnum, EnemyType, EnemyAttackType, EnemyStats } from '../types'

export const ENEMY_ATTACK_TYPES: Record<string, EnemyAttackType> = {
  explode: {
    attackDist: 30,
    attackDelay: 750,
    launchSpeed: 200,
    isExplode: true,
    damage: 1,
  },
  slash: {
    attackDist: 30,
    attackDelay: 750,
    launchSpeed: 0,
    isExplode: false,
    damage: 1,
  },
}

export const ENEMY_STATS: Record<string, EnemyStats> = {
  goblin: {
    key: 'goblin',
    attackType: ENEMY_ATTACK_TYPES['slash'],
    health: 2,
    speed: 60,
    collideDamage: 1,
    stunDuration: 400,
    stunSpeed: 200,
  },
  orc: {
    key: 'orc',
    attackType: { ...ENEMY_ATTACK_TYPES['slash'], damage: 5 },
    health: 10,
    speed: 45,
    collideDamage: 5,
    stunDuration: 600,
    stunSpeed: 200,
  },
  ogre: {
    key: 'ogre',
    attackType: { ...ENEMY_ATTACK_TYPES['slash'], damage: 10 },
    health: 50,
    speed: 15,
    collideDamage: 10,
    stunDuration: 800,
    stunSpeed: 200,
  },
  imp: {
    key: 'imp',
    attackType: ENEMY_ATTACK_TYPES['explode'],
    health: 2,
    speed: 60,
    collideDamage: 1,
    stunDuration: 400,
    stunSpeed: 200,
  },
  chort: {
    key: 'chort',
    attackType: { ...ENEMY_ATTACK_TYPES['explode'], damage: 5 },
    health: 10,
    speed: 45,
    collideDamage: 5,
    stunDuration: 750,
    stunSpeed: 400,
  },
  demon: {
    key: 'demon',
    attackType: { ...ENEMY_ATTACK_TYPES['explode'], damage: 10 },
    health: 50,
    speed: 15,
    collideDamage: 10,
    stunDuration: 1000,
    stunSpeed: 500,
  },
  lizard: {
    key: 'lizard',
    attackType: ENEMY_ATTACK_TYPES['slash'],
    health: 2,
    speed: 50,
    collideDamage: 1,
    stunDuration: 1000,
    stunSpeed: 250,
  },
  skele: {
    key: 'skele',
    attackType: ENEMY_ATTACK_TYPES['slash'],
    health: 2,
    speed: 50,
    collideDamage: 1,
    stunDuration: 1000,
    stunSpeed: 250,
  },
  shaman: {
    key: 'shaman',
    attackType: ENEMY_ATTACK_TYPES['slash'],
    health: 2,
    speed: 50,
    collideDamage: 1,
    stunDuration: 1000,
    stunSpeed: 250,
  },
}

export const ENEMY_TYPES: Record<EnemyTypeEnum, EnemyType> = {
  goblin: {
    key: 'goblin',
    offsetX: 5,
    offsetY: 5,
    offsetHealth: -35,
    offsetShadow: 25,
    sizeX: 8,
    sizeY: 8,
  },
  orc: {
    key: 'orc',
    offsetX: 5,
    offsetY: 6,
    offsetHealth: -30,
    offsetShadow: 35,
    sizeX: 8,
    sizeY: 14,
  },
  ogre: {
    key: 'ogre',
    offsetX: 7,
    offsetY: 12,
    offsetHealth: -40,
    offsetShadow: 55,
    sizeX: 17,
    sizeY: 22,
  },
  imp: {
    key: 'imp',
    offsetX: 5,
    offsetY: 5,
    offsetHealth: -35,
    offsetShadow: 25,
    sizeX: 8,
    sizeY: 8,
  },
  chort: {
    key: 'chort',
    offsetX: 5,
    offsetY: 6,
    offsetHealth: -30,
    offsetShadow: 35,
    sizeX: 8,
    sizeY: 14,
  },
  demon: {
    key: 'demon',
    offsetX: 7,
    offsetY: 12,
    offsetHealth: -40,
    offsetShadow: 55,
    sizeX: 17,
    sizeY: 22,
  },
  skele: {
    key: 'skele',
    offsetX: 5,
    offsetY: 2,
    offsetHealth: -35,
    offsetShadow: 25,
    sizeX: 8,
    sizeY: 12,
  },
  lizard: {
    key: 'lizard',
    offsetX: 3,
    offsetY: 14,
    offsetHealth: -28,
    offsetShadow: 42,
    sizeX: 12,
    sizeY: 12,
  },
  shaman: {
    key: 'shaman',
    offsetX: 5,
    offsetY: 6,
    offsetHealth: -30,
    offsetShadow: 35,
    sizeX: 8,
    sizeY: 14,
  },
}
