export const CAMERA_FADE = 750
export const ANIMS = [
  {
    prefix: 'knight_m_idle_anim_f',
    key: 'player-idle',
    start: 0,
    end: 3,
    frameRate: 5,
    repeat: -1,
  },
  {
    prefix: 'knight_m_run_anim_f',
    key: 'player-walk',
    start: 0,
    end: 3,
    frameRate: 10,
    repeat: -1,
  },
  {
    prefix: 'skelet_run_anim_f',
    key: 'skele-idle',
    start: 3,
    end: 3,
    frameRate: 2,
    repeat: -1,
  },
  {
    prefix: 'skelet_run_anim_f',
    key: 'skele-walk',
    start: 0,
    end: 3,
    frameRate: 6,
    repeat: -1,
  },
  {
    prefix: 'Slash3_color4_frame',
    key: 'slash-1',
    start: 1,
    end: 9,
    frameRate: 30,
    repeat: 0,
  },
  {
    prefix: 'Slash_color4_frame',
    key: 'slash-2',
    start: 1,
    end: 4,
    frameRate: 10,
    repeat: 0,
  },
  {
    prefix: 'Slash_color4_frame',
    key: 'slash-3',
    start: 4,
    end: 9,
    frameRate: 20,
    repeat: 0,
  },
  {
    prefix: 'Slash2_color4_frame',
    key: 'slash-4',
    start: 1,
    end: 9,
    frameRate: 20,
    repeat: 0,
  },
]
